version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      target: dev
    restart: always
    command: sh -c "npx prisma generate && npm run dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - DATABASE_URL=postgresql://user:password@db:5432/mydb?schema=public
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
